### ISSUE TITLE
undefined: libp2p.NoEncryption error prevents application to compile and run

### ISSUE THREAD

**Issue by grempe** [mycoralhealth/blockchain-tutorial#14]
From blog post:

https://medium.com/coinmonks/code-a-simple-p2p-blockchain-in-go-46662601f417

If not commented out, this line breaks compilation of the sample program:

https://github.com/mycoralhealth/blockchain-tutorial/blob/master/p2p/main.go#L74

linter declares `undefined libp2p.NoEncryption`

Trying to run it results in:

```
$ go run main.go -l 10000 -secio
# command-line-arguments
./main.go:75:23: undefined: libp2p.NoEncryption
```

Commenting it out allows the program to run as expected.

**Comment by nosequeldeebee** [comment]
It looks like `go-libp2p` did indeed remove that method: https://godoc.org/github.com/libp2p/go-libp2p

Do you want to submit a pull request with that `!secio` section removed from the code?

**Comment by jorge-abarca** [comment]
While `go-libp2p` removed the `NoEncryption` method, the contributors added a variable that seems to be its replacement: `NoSecurity`.

You can see [in their next commit that their echo example for a basic host changed `NoEncryption()` for `NoSecurity`](https://github.com/libp2p/go-libp2p/commit/41c683485015bca19626138f18fa0027b5a8243d#diff-98e18e816d91c9c6585829338d6155debdfa71ceba3e07fc71444b9194e5aaa4).

I see [the whole check was removed in #14 from the blockchain-tutorial repository](https://github.com/nosequeldeebee/blockchain-tutorial/commit/a555824d82d66a62ea57077cdc0ec3c5ca0d1ca9#diff-172a69f0f7c175df09cfffb1459b63fa64412e22d1dc403e8906a7538af9e09c), since the `secio` parameter and flag are still a part of the example, perhaps it would make sense to add the following lines of code [on line 73](https://github.com/nosequeldeebee/blockchain-tutorial/blob/645ce285b13199f3c3a39c6cd765987acba1aea3/p2p/main.go#L73):
```
if !secio {
	opts = append(opts, libp2p.NoSecurity)
}
```
These would be [the replacement lines of `go-libp2p`'s example](https://github.com/libp2p/go-libp2p/blob/41c683485015bca19626138f18fa0027b5a8243d/examples/echo/main.go#L51-L53). They seem to [still be used at this moment](https://github.com/libp2p/go-libp2p/blob/master/examples/echo/main.go#L81-L83).

I will submit a pull request with this change if that is more convenient for you.

**Comment by jorge-abarca** [comment]
I submitted PR #39, if you are interested to bring back the `secio` check functionality.
