### ISSUE TITLE
dial failed

### ISSUE THREAD

**Issue by hot3246624** [mycoralhealth/blockchain-tutorial#20]
Failed to dial through 0 known relay hosts

2018/10/23 20:41:17 I am /p2p-circuit/ipfs/QmVEiBiyRV1ntWNTHimziDHzFu41LDqV9GaxbYztavXSVj
2018/10/23 20:41:17 Now run "go run main.go -l 10002 -d /p2p-circuit/ipfs/QmVEiBiyRV1ntWNTHimziDHzFu41LDqV9GaxbYztavXSVj -secio" on a different terminal
2018/10/23 20:41:17 opening stream
20:41:17.070  INFO     swarm2: got error on dial to /p2p-circuit: <peer.ID Qm*avXSVj> --> <peer.ID Qm*EMYDLm> dial attempt failed: Failed to dial through 0 known relay hosts swarm_dial.go:382
2018/10/23 20:41:17 dial attempt failed: <peer.ID Qm*avXSVj> --> <peer.ID Qm*EMYDLm> dial attempt failed: Failed to dial through 0 known relay hosts

**Comment by nosequeldeebee** [comment]
please provide more detail. Which `main.go` file are you running? Which project? P2P? What have you tried?

**Comment by hot3246624** [comment]
direct to run p2p/main.go follow your paper:https://medium.com/@mycoralhealth/code-a-simple-p2p-blockchain-in-go-46662601f417

**Comment by hot3246624** [comment]
in p2p directory:
1. in 1st terminal `go run main.go -secio -l 10000`
2. in 2nd terminal `go run main.go -l 10002 -d /p2p-circuit/ipfs/QmYJ4ZizRBPLYcunr1JkEMBSQvCXgPvwXAqC5Xoi8CQKrt -secio`
then raise error:
======
I am /p2p-circuit/ipfs/QmYJ4ZizRBPLYcunr1JkEMBSQvCXgPvwXAqC5Xoi8CQKrt
2018/10/29 11:00:37 Now run "go run main.go -l 10002 -d /p2p-circuit/ipfs/QmYJ4ZizRBPLYcunr1JkEMBSQvCXgPvwXAqC5Xoi8CQKrt -secio" on a different terminal
2018/10/29 11:00:37 opening stream
11:00:37.779  INFO     swarm2: got error on dial to /p2p-circuit: <peer.ID Qm*8CQKrt> --> <peer.ID Qm*KEkLNR> dial attempt failed: Failed to dial through 0 known relay hosts swarm_dial.go:382
2018/10/29 11:00:37 dial attempt failed: <peer.ID Qm*8CQKrt> --> <peer.ID Qm*KEkLNR> dial attempt failed: Failed to dial through 0 known relay hosts
exit status 1
======
that is all,  is there somewhere need to set the config about relay hosts?

**Comment by ArshadAQ** [comment]
This is because a call to `basicHost.Addrs()` returns all addresses. This call returns a Multiaddr slice.
It looks like this : `[/p2p-circuit /ip4/127.0.0.1/tcp/10001]`.

The current code indexes this slice with zero to select the required address and hence the above error with "p2p-circuit". 

An impulse decision would make you to index this slice with an index of 1 to get the correct address.
However, the catch is that, there is no specific order in which the elements of this slice would return.

A hack is to check whether the element of the slice starts with "/ip4" and select that address. 
A PR has been submitted for the same.

**Comment by nosequeldeebee** [comment]
fixed by #24 thanks @ArshadAQ
